### ISSUE TITLE
Opencv issue

### ISSUE THREAD

**Issue by eloycoto** [GuillaumeDesforges/fix-python#13]
When installing opencv:

Preparation:
```
$ -->
$ --> ls
gl.nix
$ --> cat gl.nix
(
  let pkgs = import (builtins.getFlake "nixpkgs") { };
  in [
    pkgs.gcc.cc
    pkgs.glibc
    pkgs.zlib
    pkgs.libGL
  ]
)

$ --> nix run nixpkgs#python311 -- -m venv .venv --copies
$ --> .venv/bin/pip install opencv-python
Collecting opencv-python
  Using cached opencv_python-4.9.0.80-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Collecting numpy>=1.21.2 (from opencv-python)
  Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Using cached opencv_python-4.9.0.80-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (62.2 MB)
Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
Installing collected packages: numpy, opencv-python
Successfully installed numpy-1.26.4 opencv-python-4.9.0.80
$ --> fix-python --venv $VENV_FOLDER --with-torch --libs ./gl.nix
```

Issue:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/work/fix-python/fix-python/.venv/lib/python3.11/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/runner/work/fix-python/fix-python/.venv/lib/python3.11/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/glfr70gi7hfaj50mwj2431p8bg60fhqw-python3-3.11.9/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
```

GitHub Action:

```
name: Check

on:
  push:
    branches:
      - main
      - master
      - action
  pull_request:
    branches:
      - main
      - master

jobs:
  check-numpy-import:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Nix
        uses: cachix/install-nix-action@v22

      - name: Install Python 3.11 with Nix
        run: nix --extra-experimental-features nix-command --extra-experimental-features flakes run nixpkgs#python311 -- -m venv .venv --copies

      - name: Install numpy
        run: .venv/bin/pip install numpy opencv-python

      - name: Fix numpy import issue
        run: ./fix-python --venv .venv --libs ./gl.nix

      - name: Check numpy import after fix
        run: .venv/bin/python -c 'import cv2'
```

**Comment by GuillaumeDesforges** [comment]
```
$ nix-locate libgthread-2.0.so.0
```

gives me `glib` (among others), could you try adding that to gl.nix?

**Comment by eloycoto** [comment]
ok, I got it working, for documenting it:

Action:
```
name: Check

on:
  push:
    branches:
      - main
      - master
      - action
      - opencv
  pull_request:
    branches:
      - main
      - master

jobs:
  check-numpy-import:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Nix
        uses: cachix/install-nix-action@v22

      - name: Install Python 3.11 with Nix
        run: nix --extra-experimental-features nix-command --extra-experimental-features flakes run nixpkgs#python311 -- -m venv .venv --copies

      - name: check that using it on numpy works
        run: |
          echo "Install numpy"
          .venv/bin/pip install numpy opencv-python
          echo "Run fix-python"
          ./fix-python --venv .venv --libs ./gl.nix
          echo "Check opencv works"
          .venv/bin/python -c 'import cv2'
```

And gl:
```
(
  let pkgs = import (builtins.getFlake "nixpkgs") { };
  in [
    pkgs.gcc.cc
    pkgs.glibc
    pkgs.zlib
    pkgs.libGL
    pkgs.glib
  ]
)
```
